// Copies the generated third-party notices into the client's static assets, so they ship.
//
// NOTICE.md is generated by tools/licences/check-licences.ts and lives at the repo root, where
// it is reviewed in pull requests. That is the right home for it — but it is NOT served, NOT
// bundled, and no UI linked to it, so until now every notice this project generated reached
// nobody.
//
// That matters beyond tidiness. Copernicus Article 6(c) requires its liability sentence to
// appear "in a licence or any legal warning or notice covering their distribution or
// communication to the General Public"; a file in a git repository is not that. The same goes
// for the not-for-navigation warning, which is a safety statement, and for the USGS
// modification disclosure. Generating a compliant notice and never showing it is the same
// declared-not-done shape the licence register exists to close.
//
// Runs before the Vite build, and fails loudly rather than shipping without notices.

import { copyFileSync, mkdirSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..", "..", "..");

const SOURCE = join(REPO, "NOTICE.md");
const DEST_DIR = join(HERE, "..", "client", "public", "legal");
const DEST = join(DEST_DIR, "notices.md");

let notice;
try {
  notice = readFileSync(SOURCE, "utf8");
} catch (error) {
  console.error(
    `copy-legal: could not read ${SOURCE}: ${error.message}\n`
    + "Refusing to continue rather than ship a product with no third-party notices. "
    + "Regenerate with tools/licences/check-licences.ts --emit-notice NOTICE.md.",
  );
  process.exit(1);
}

if (!notice.trim()) {
  console.error(
    `copy-legal: ${SOURCE} is empty. Shipping an empty notices file would look like compliance `
    + "and be none.",
  );
  process.exit(1);
}

mkdirSync(DEST_DIR, { recursive: true });

// Nothing but the generated notices may live here. The first version of this change also put
// a DRAFT end-user terms document in this directory and linked it from the settings panel as
// "Terms" — a file headed "NOT IN FORCE", with liability and warranty left as placeholders,
// presented to users as the product's terms. Review caught it; this makes it not recur.
//
// An unratified legal document served to users is worse than none: a reader has no way to know
// it is a draft, and the placeholders sit exactly where the protections would be.
const stray = readdirSync(DEST_DIR).filter((name) => name !== "notices.md");
if (stray.length) {
  console.error(
    `copy-legal: ${DEST_DIR} contains ${stray.map((s) => JSON.stringify(s)).join(", ")}.\n`
    + "Only the generated notices may ship from here. A legal document in this directory is "
    + "served to users and linked from the product, so it must be one somebody has approved — "
    + "keep drafts under tools/licences/ until then.",
  );
  process.exit(1);
}

copyFileSync(SOURCE, DEST);
console.log(`copy-legal: NOTICE.md -> client/public/legal/notices.md (${notice.length} bytes)`);
