#!/usr/bin/env python3
# Copyright 2026 ResQ Systems, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Regenerate favicon.svg: the canonical ResQ mark on the viz console plate."""
import pathlib
from mark import mark_body

OUT = pathlib.Path(__file__).resolve().parent / "../../src/ResQ.Viz.Web/client/public/favicon.svg"
SCALE = 0.72
OFF = 512 * (1 - SCALE) / 2

OUT.write_text(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512"
     role="img" aria-label="ResQ Viz">
  <title>ResQ Viz</title>
  <!--
    Generated by scripts/brand/generate-favicon.py — do not hand-edit.
    The mark is the canonical brand vector (scripts/brand/resq-mark-color.svg),
    vendored verbatim; per the brand style guide it must not be restyled. Only
    the plate is viz-specific: console surface #111319, matching
    site.webmanifest theme_color and index.html <meta name="theme-color">.
  -->
  <rect width="512" height="512" rx="112" fill="#111319"/>
  <g transform="translate({OFF:.1f},{OFF:.1f}) scale({SCALE})">
    {mark_body()}
  </g>
</svg>
''')
print(f"wrote {OUT.resolve()}")
